Repository AquaToken/soroban-amm, pull requests merged in 2024-10, with the labels that each got.

#99 [Chore] LP token migration cleanup
  liquidity_pool/src/contract.rs
  liquidity_pool/src/pool_interface.rs
  liquidity_pool_stableswap/src/contract.rs
  liquidity_pool_stableswap/src/pool_interface.rs
  token_share/src/lib.rs
Labels: cleanup

#91 [Bugfix] Fix outstanding reward value overflow
  liquidity_pool_router/src/contract.rs
  liquidity_pool_router/src/test.rs
Labels: bug

#90 [Improvement] H03 add tokens decimal into pool
  contracts/soroban_token.wasm
  liquidity_pool_stableswap/src/contract.rs
  liquidity_pool_stableswap/src/lib.rs
  liquidity_pool_stableswap/src/normalize.rs
  liquidity_pool_stableswap/src/plane.rs
  liquidity_pool_stableswap/src/pool_constants.rs
  liquidity_pool_stableswap/src/pool_interface.rs
  liquidity_pool_stableswap/src/storage.rs
  liquidity_pool_stableswap/src/test.rs
Labels: enhancement

#101 [Feature] Return unused reward to router
  liquidity_pool/src/contract.rs
  liquidity_pool/src/pool_interface.rs
  liquidity_pool/src/test.rs
  liquidity_pool/src/testutils.rs
  liquidity_pool_stableswap/src/contract.rs
  liquidity_pool_stableswap/src/pool_interface.rs
  liquidity_pool_stableswap/src/test.rs
  liquidity_pool_stableswap/src/testutils.rs
Labels: enhancement

#102 [Feature] L07 Add admin events
  access_control/src/access.rs
  access_control/src/events.rs
  access_control/src/lib.rs
  fees_collector/src/contract.rs
  fees_collector/src/test.rs
  liquidity_pool/src/contract.rs
  liquidity_pool/src/test.rs
  liquidity_pool_liquidity_calculator/src/contract.rs
  liquidity_pool_liquidity_calculator/src/test.rs
  liquidity_pool_plane/src/contract.rs
  liquidity_pool_plane/src/test.rs
  liquidity_pool_router/src/contract.rs
  liquidity_pool_router/src/test.rs
  liquidity_pool_stableswap/src/contract.rs
  liquidity_pool_stableswap/src/events.rs
  liquidity_pool_stableswap/src/lib.rs
  liquidity_pool_stableswap/src/test.rs
  rewards/src/events.rs
  rewards/src/lib.rs
  token/src/contract.rs
  token/src/test.rs
Labels: enhancement

#103 [Chore] Uniform input validation
  liquidity_pool/src/contract.rs
  liquidity_pool_router/src/contract.rs
  liquidity_pool_router/src/errors.rs
  liquidity_pool_router/src/pool_utils.rs
  liquidity_pool_router/src/storage.rs
  liquidity_pool_stableswap/src/contract.rs
  liquidity_pool_stableswap/src/pool_constants.rs
  liquidity_pool_validation_errors/src/lib.rs
  utils/src/lib.rs
  utils/src/token_utils.rs
Labels: cleanup
